export enum Role {
  ADMIN = "ADMIN",
  COORDINATOR = "COORDINATOR",
  DESIGNER = "DESIGNER",
  INTERN = "INTERN"
}

export enum ProjectStatus {
  ACTIVE = "ACTIVE",
  ON_HOLD = "ON_HOLD",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED"
}

export enum DisciplineType {
  HYDRAULIC = "HYDRAULIC",
  SANITARY = "SANITARY",
  FIRE_PROTECTION = "FIRE_PROTECTION",
  SPRINKLER = "SPRINKLER",
  PRESSURIZED_STAIR = "PRESSURIZED_STAIR",
  ELECTRICAL = "ELECTRICAL",
  SPDA = "SPDA",
  TELECOM = "TELECOM",
  HVAC = "HVAC",
  GAS = "GAS",
  AUTOMATION = "AUTOMATION",
  EXHAUST = "EXHAUST",
  VACUUM = "VACUUM",
  OTHER = "OTHER"
}

export enum DisciplineStatus {
  NOT_STARTED = "NOT_STARTED",
  IN_PROGRESS = "IN_PROGRESS",
  IN_REVIEW = "IN_REVIEW",
  COMPLETED = "COMPLETED"
}

export enum TaskStatus {
  TODO = "TODO",
  ON_SCHEDULE = "ON_SCHEDULE",
  OVERDUE = "OVERDUE",
  IN_PROGRESS = "IN_PROGRESS",
  AWAITING_REVIEW = "AWAITING_REVIEW",
  IN_ANALYSIS = "IN_ANALYSIS",
  AWAITING_DEFINITION = "AWAITING_DEFINITION",
  FINISHED = "FINISHED"
}

export enum Priority {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  URGENT = "URGENT"
}

export enum NotificationType {
  TASK_ASSIGNED = "TASK_ASSIGNED",
  TASK_UPDATED = "TASK_UPDATED",
  COMMENT_ADDED = "COMMENT_ADDED",
  DUE_SOON = "DUE_SOON"
}
